spring.application.name=streaming
spring.datasource.url=jdbc:postgresql://localhost:5432/streaming_db
spring.datasource.username=eduhaidu
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update